apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-externalsecret-tls
  namespace: kc
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-back
    kind: ClusterSecretStore
  target:
    name: keycloak-externalsecret-tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: secret/kc-kdc/keycloak/0.0.1
        property: kc-kdc-cert
        # version: "1"
        decodingStrategy: Base64
    - secretKey: tls.key
      remoteRef:
        key: secret/kc-kdc/keycloak/0.0.1
        property: kc-kdc-key
        # version: "1"
        decodingStrategy: Base64
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-externalsecret-tls
  namespace: kc
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-back
    kind: ClusterSecretStore
  target:
    name: rabbitmq-externalsecret-tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: secret/kc-kdc/rabbitmq/0.0.1
        property: rq-kdc-cert
        # version: "1"
        decodingStrategy: Base64
    - secretKey: tls.key
      remoteRef:
        key: secret/kc-kdc/rabbitmq/0.0.1
        property: rq-kdc-key
        # version: "1"
        decodingStrategy: Base64
