apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kong-externalsecret-tls
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-back
    kind: ClusterSecretStore
  target:
    name: kong-externalsecret-tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: secret/kc-kdc/kong/0.0.1
        property: kong-kdc-cert
        decodingStrategy: Base64
    - secretKey: tls.key
      remoteRef:
        key: secret/kc-kdc/kong/0.0.1
        property: kong-kdc-key
        decodingStrategy: Base64
