apiVersion: v1
kind: Service
metadata:
  name: kong-service
  labels:
    app: kong
spec:
  ports:
    - name: proxy
      port: {{ .Values.kong.proxy.http.servicePort }}
      targetPort: {{ .Values.kong.proxy.http.containerPort }}
      protocol: TCP
    - name: proxy-ssl
      port: {{ .Values.kong.proxy.tls.servicePort }}
      targetPort: {{ .Values.kong.proxy.tls.containerPort }}
      protocol: TCP
    - name: admin
      port: {{ .Values.kong.admin.http.servicePort }}
      targetPort: {{ .Values.kong.admin.http.containerPort }}
      protocol: TCP
    - name: admin-ssl
      port: {{ .Values.kong.admin.tls.servicePort }}
      targetPort: {{ .Values.kong.admin.tls.containerPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/instance: kong

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
      nodePort: {{ .Values.postgresql.service.nodePort }}
  selector:
    app: postgres
  type: NodePort

