version: '3.8'

services:
  caddy:
    image: caddy:2.7-alpine
    container_name: caddy-proxy
    restart: unless-stopped
    network_mode: "host"  # This allows direct access to host network
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./site:/usr/share/nginx/html:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./logs:/var/log/caddy

volumes:
  caddy_data:
  caddy_config:
